export const ALL_LOAN_LOADING = 'ALL/LOAN/LOADING'
export const ALL_LOAN_SUCCESS = 'ALL/LOAN/SUCCES'
export const ALL_LOAN_ERROR = 'ALL/LOAN/ERROR'

export const LENDER_LOAN_LOADING = 'LENDER/LOAN/LOADING'
export const LENDER_LOAN_SUCCESS = 'LENDER/LOAN/SUCCES'
export const LENDER_LOAN_ERROR = 'LENDER/LOAN/ERROR'

export const BORROWER_LOAN_LOADING = 'BORROWER/LOAN/LOADING'
export const BORROWER_LOAN_SUCCESS = 'BORROWER/LOAN/SUCCES'
export const BORROWER_LOAN_ERROR = 'BORROWER/LOAN/ERROR'

export const BORROWER_PAY_LOADING = 'BORROWER/PAY/LOADING'
export const BORROWER_PAY_SUCCESS = 'BORROWER/PAY/SUCCES'
export const BORROWER_PAY_ERROR = 'BORROWER/PAY/ERROR'

export const LANDER_INVEST_LOADING = 'LANDER/INVEST/LOADING'
export const LANDER_INVEST_SUCCESS = 'LANDER/INVEST/SUCCES'
export const LANDER_INVEST_ERROR = 'LANDER/INVEST/ERROR'

export const BORROWER_AMOUNT_LOADING = 'BORROWER/AMOUNT/LOADING'
export const BORROWER_AMOUNT_SUCCESS = 'BORROWER/AMOUNT/SUCCES'
export const BORROWER_AMOUNT_ERROR = 'BORROWER/AMOUNT/ERROR'

export const LANDER_GET_AMOUNT_LOADING = 'LANDER/GET/AMOUNT/LOADING'
export const LANDER_GET_AMOUNT_SUCCESS = 'LANDER/GET/AMOUNT/SUCCES'
export const LANDER_GET_AMOUNT_ERROR = 'LANDER/GET/AMOUNT/ERROR'