export const PINJAMAN_LOADING = 'PINJAMAN/LOADING'
export const PINJAMAN_SUCCESS = 'PINJAMAN/SUCCES'
export const PINJAMAN_ERROR = 'PINJAMAN/ERROR'

export const PINJAMAN_BY_ID_LOADING = 'PINJAMAN/BY/ID/LOADING'
export const PINJAMAN_BY_ID_SUCCESS = 'PINJAMAN/BY/ID/SUCCES'
export const PINJAMAN_BY_ID_ERROR = 'PINJAMAN/BY/ID/ERROR'

export const ADD_PINJAMAN_LOADING = 'ADD/PINJAMAN/LOADING'
export const ADD_PINJAMAN_SUCCESS = 'ADD/PINJAMAN/SUCCES'
export const ADD_PINJAMAN_ERROR = 'ADD/PINJAMAN/ERROR'

export const EDIT_PINJAMAN_LOADING = 'EDIT/PINJAMAN/LOADING'
export const EDIT_PINJAMAN_SUCCESS = 'EDIT/PINJAMAN/SUCCES'
export const EDIT_PINJAMAN_ERROR = 'EDIT/PINJAMAN/ERROR'

export const DELETE_PINJAMAN_LOADING = 'DELETE/PINJAMAN/LOADING'
export const DELETE_PINJAMAN_SUCCESS = 'DELETE/PINJAMAN/SUCCES'
export const DELETE_PINJAMAN_ERROR = 'DELETE/PINJAMAN/ERROR'