export const LOAN_LENDER_LOADING = 'LOAN/LENDER/LOADING'
export const LOAN_LENDER_SUCCESS = 'LOAN/LENDER/SUCCES'
export const LOAN_LENDER_ERROR = 'LOAN/LENDER/ERROR'

export const LOAN_BORROWER_LOADING = 'LOAN/BORROWER/LOADING'
export const LOAN_BORROWER_SUCCESS = 'LOAN/BORROWER/SUCCES'
export const LOAN_BORROWER_ERROR = 'LOAN/BORROWER/ERROR'

export const BORROWER_PAY_LOADING = 'BORROWER/PAY/LOADING'
export const BORROWER_PAY_SUCCESS = 'BORROWER/PAY/SUCCES'
export const BORROWER_PAY_ERROR = 'BORROWER/PAY/ERROR'

export const LANDER_INVEST_LOADING = 'LANDER/INVEST/LOADING'
export const LANDER_INVEST_SUCCESS = 'LANDER/INVEST/SUCCES'
export const LANDER_INVEST_ERROR = 'LANDER/INVEST/ERROR'

export const BORROWER_AMOUNT_LOADING = 'BORROWER/AMOUNT/LOADING'
export const BORROWER_AMOUNT_SUCCESS = 'BORROWER/AMOUNT/SUCCES'
export const BORROWER_AMOUNT_ERROR = 'BORROWER/AMOUNT/ERROR'

export const LANDER_GET_AMOUNT_LOADING = 'LANDER/GET/AMOUNT/LOADING'
export const LANDER_GET_AMOUNT_SUCCESS = 'LANDER/GET/AMOUNT/SUCCES'
export const LANDER_GET_AMOUNT_ERROR = 'LANDER/GET/AMOUNT/ERROR'