export const LOGIN_USER_LOADING = 'LOGIN/USER/LOADING'
export const LOGIN_USER_SUCCESS = 'LOGIN/USER/SUCCES'
export const LOGIN_USER_ERROR = 'LOGIN/USER/ERROR'

export const REGISTER_USER_LOADING = 'REGISTER/USER/LOADING'
export const REGISTER_USER_SUCCESS = 'REGISTER/USER/SUCCES'
export const REGISTER_USER_ERROR = 'REGISTER/USER/ERROR'

export const USER_LOADING = 'USER/LOADING'
export const USER_SUCCESS = 'USER/SUCCES'
export const USER_ERROR = 'USER/ERROR'

export const USER_BY_ID_LOADING = 'USER/BY/ID/LOADING'
export const USER_BY_ID_SUCCESS = 'USER/BY/ID/SUCCES'
export const USER_BY_ID_ERROR = 'USER/BY/ID/ERROR'

export const EDIT_USER_LOADING = 'EDIT/USER/LOADING'
export const EDIT_USER_SUCCESS = 'EDIT/USER/SUCCES'
export const EDIT_USER_ERROR = 'EDIT/USER/ERROR'

export const DELETE_USER_LOADING = 'DELETE/USER/LOADING'
export const DELETE_USER_SUCCESS = 'DELETE/USER/SUCCES'
export const DELETE_USER_ERROR = 'DELETE/USER/ERROR'

