const tanggal = new Date();
console.log(tanggal);
console.log(tanggal.getTime(), "milisecond");
console.log(tanggal.getDay(), "day");
console.log(tanggal.getHours(), "hour");
console.log(tanggal.getMinutes(), "minutes");
console.log(tanggal.toLocaleString("id-ID"), "Indo");
console.log(tanggal.toUTCString(), "pusat");
console.log(tanggal.getUTCHours(), "pusat");
console.log(5 * 60 * 1000);
