export const BORROWER_LOADING = 'BORROWER/LOADING'
export const BORROWER_SUCCESS = 'BORROWER/SUCCES'
export const BORROWER_ERROR = 'BORROWER/ERROR'

export const BORROWER_BY_ID_LOADING = 'BORROWER/BY/ID/LOADING'
export const BORROWER_BY_ID_SUCCESS = 'BORROWER/BY/ID/SUCCES'
export const BORROWER_BY_ID_ERROR = 'BORROWER/BY/ID/ERROR'

export const ADD_BORROWER_LOADING = 'ADD/BORROWER/LOADING'
export const ADD_BORROWER_SUCCESS = 'ADD/BORROWER/SUCCES'
export const ADD_BORROWER_ERROR = 'ADD/BORROWER/ERROR'

export const EDIT_BORROWER_LOADING = 'EDIT/BORROWER/LOADING'
export const EDIT_BORROWER_SUCCESS = 'EDIT/BORROWER/SUCCES'
export const EDIT_BORROWER_ERROR = 'EDIT/BORROWER/ERROR'

export const DELETE_BORROWER_LOADING = 'DELETE/BORROWER/LOADING'
export const DELETE_BORROWER_SUCCESS = 'DELETE/BORROWER/SUCCES'
export const DELETE_BORROWER_ERROR = 'DELETE/BORROWER/ERROR'

