export const LANDER_LOADING = 'LANDER/LOADING'
export const LANDER_SUCCESS = 'LANDER/SUCCES'
export const LANDER_ERROR = 'LANDER/ERROR'

export const LANDER_BY_ID_LOADING = 'LANDER/BY/ID/LOADING'
export const LANDER_BY_ID_SUCCESS = 'LANDER/BY/ID/SUCCES'
export const LANDER_BY_ID_ERROR = 'LANDER/BY/ID/ERROR'

export const ADD_LANDER_LOADING = 'ADD/LANDER/LOADING'
export const ADD_LANDER_SUCCESS = 'ADD/LANDER/SUCCES'
export const ADD_LANDER_ERROR = 'ADD/LANDER/ERROR'

export const EDIT_LANDER_LOADING = 'EDIT/LANDER/LOADING'
export const EDIT_LANDER_SUCCESS = 'EDIT/LANDER/SUCCES'
export const EDIT_LANDER_ERROR = 'EDIT/LANDER/ERROR'

export const DELETE_LANDER_LOADING = 'DELETE/LANDER/LOADING'
export const DELETE_LANDER_SUCCESS = 'DELETE/LANDER/SUCCES'
export const DELETE_LANDER_ERROR = 'DELETE/LANDER/ERROR'