export { default as DasboardBorower } from './Borrower/DasboardBorower'
export { default as TempatMinjam } from './Borrower/TempatMinjam'
export { default as Home } from './Home/Home'
export { default as Lander } from './Lander/Lander'
export { default as Login } from './Login/Login'
export { default as Register } from './Register/Register'